### PR TITLE
Refactoring the validator and fixing some small bugs.

### LINKED ISSUE #51: `cardano-explorer-api-validate` is failing.
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `198c77cf079901fba620944a17de6d79fc014145` |
| Platform     | All         |
| Installation | From source            |

# Steps to Reproduce

``` sh
$ cardano-explorer-api-validate validate --count 10
```

## Expected behavior

When the validator passes it should display a message like "Balance for ... is non-negative."

## Actual behavior
 
When it throws one of these two errors:

```
Test #1:
queryRandomRedeemAddress: Lookup address by index failed
```

...or:

```
Test #1:
  Address balance is negative: 
  Address: 2657WMsDfac61hnkvpPkUonfxNWpoW77QiQLfxUPiWZYW4r2694YGviDzpR7wkyuH
    type: CPubKeyAddress
    tx count: 1
    balance: -32000000000000000
    fees: 166016
```
---

# Resolution 

---

# QA

### PR DESCRIPTION
**Pull request by krisajenkins**
# Issue Number

Fixes #51.

# Overview

- Refactoring CCoin to simplify some calculation code.
- Refactoring. `if True then x ...` is _always_ `x`.
- Bugfix for the release.nix build of cardano-rest-macos64.
- Bugfix: cardano-explorer-api-validate wrongly claims to have a default count of 10.
- Bugfix: cardano-explorer-api-validate is intermittently failing to find a random row.

# Comments

### CODE REVIEW

File: explorer-api/app/Explorer/Web/Validate/Random.hs [hunk 1]
```diff
@@ -45,70 +39,54 @@ import Database.Esqueleto
...
+             pure (txOut ^. TxOutAddress)
+    pure $ maybeToEither errMsg unValue (listToMaybe res)
   where
-    errMsg :: LookupFail
-    errMsg = DbLookupMessage "queryRandomRedeemAddress: Lookup address by index failed"
-
-mkTxOutId :: Word -> TxOutId
-mkTxOutId = TxOutKey . fromIntegral
+    errMsg ::  LookupFail
+    errMsg = DbLookupMessage "queryRandomRedeemAddress: Lookup address"
```
Comment (intricate) [inline explorer-api/app/Explorer/Web/Validate/Random.hs:79]: Was this error message shortened on purpose?

File: explorer-api/app/cardano-explorer-api-validate.hs [hunk 2]
```diff
@@ -53,7 +53,9 @@ pCommand =
 
     pCount :: Parser Word
     pCount =
-      read <$> Opt.strOption
+      Opt.option Opt.auto
         (  Opt.long "count"
-        <> Opt.help "The number of validations to run (default is 10)."
+        <> Opt.help "The number of validations to run."
+        <> Opt.value 10
```
Comment (intricate) [inline explorer-api/app/cardano-explorer-api-validate.hs:59]: :+1:

File: explorer-api/app/Explorer/Web/Validate/Random.hs (hunk 1 above)
Comment (krisajenkins) [reply explorer-api/app/Explorer/Web/Validate/Random.hs]: Ah thanks. The change was deliberate, but I intended to replace it with, "Lookup random X failed".

Fixed. 👍

File: explorer-api/src/Explorer/Web/ClientTypes.hs [hunk 3]
```diff
@@ -128,23 +127,17 @@ newtype CNetwork = CNetwork Text
 newtype CCoin = CCoin
     { unCCoin :: Integer
     } deriving (Show, Generic, Eq)
+      deriving newtype (Num, Ord)
```
Comment (erikd) [inline explorer-api/src/Explorer/Web/ClientTypes.hs:130]: Add a `Num` instance removes some of the type safety the newtype wrapper was intended to add.

Comment (krisajenkins) [reply explorer-api/src/Explorer/Web/ClientTypes.hs:130]: Interesting. Could you give me an example?

I know you could now do constants like `let a = 0 :: CCoin`, but that seems fine to me. (Though I welcome debate. :-) )

You'd still be prevented from making mistakes this though:

```
let a = 5 :: Int
    b = 4 :: CCoin
in a + b
```

What am I missing? 🤔
